### ISSUE TITLE
There is no  TZImagePickerController.framework in bundle

### ISSUE THREAD

**Issue by rptwsthi** [liaoyuan-io/react-native-multiple-image-picker#14]
Description says, 

- Copy TZImagePickerController.framework to your Framework folder.
- Add TZImagePickerController.framework to your Framework group and Embedded Binaries section in Target->General .

But there is no such bundle available inside node-module -> react-native-multiple-image-picker. Although there is this folder,  named **TZImagePickerController** and I converted it into a framework (by adding .framework at the end) but it didn't work. It throws following errors:

Showing Recent Errors Only
No such file or directory: '/Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios/TZImagePickerController/TZImagePickerController/TZImagePickerController/TZPhotoPreviewCell.m'

No input files

CompileC /Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/Objects-normal/arm64/TZImagePickerController.o TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImagePickerController.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/technologies33/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/technologies33/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fembed-bitcode-marker -index-store-path /Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Index/DataStore -iquote /Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/RCTMultipleImagePicker-generated-files.hmap -I/Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/RCTMultipleImagePicker-own-target-headers.hmap -I/Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/RCTMultipleImagePicker-all-target-headers.hmap -iquote /Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/RCTMultipleImagePicker-project-headers.hmap -I/Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Products/Debug-iphoneos/include -I/Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios/../node_modules/react-native/React -I/Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios/../../react-native/React -I/Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios/../../node_modules/react-native/React -I/Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios/../Example/node_modules/react-native/React/** -I/Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/DerivedSources/arm64 -I/Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/DerivedSources -F/Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Products/Debug-iphoneos -MMD -MT dependencies -MF /Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/Objects-normal/arm64/TZImagePickerController.d --serialize-diagnostics /Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/Objects-normal/arm64/TZImagePickerController.dia -c /Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios/TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImagePickerController.m -o /Users/technologies33/Library/Developer/Xcode/DerivedData/mesmobile-aqyjedpwgagpbmdkxfjeuhvbslvf/Build/Intermediates.noindex/RCTMultipleImagePicker.build/Debug-iphoneos/RCTMultipleImagePicker.build/Objects-normal/arm64/TZImagePickerController.o

clang: error: no such file or directory: '/Work/Arpit/MESSales/mesmobile/node_modules/react-native-multiple-image-picker/ios/TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImagePickerController.m'
clang: error: no input files

**Comment by cnjsstong** [comment]
https://github.com/liaoyuan-io/react-native-multiple-image-picker/tree/18261397342ac74376c45fa18dcfc4940b933034/ios/TZImagePickerController.framework

This is the framework. 

Let me check why you don't have this in module folder. The npm module is possibly out-dated.

**Comment by cnjsstong** [comment]
Hi @rptwsthi ,

I've published the module to npm again. Now you can install the updated v0.7.2 from npm. Thanks for your feedback.

I will close this issue for now. If you have any other questions, please reopen it.
