### ISSUE TITLE
No image to choose when first authorized app to access photos.

### ISSUE THREAD

**Issue by jaggerwang** [liaoyuan-io/react-native-multiple-image-picker#4]
### ENV

RN 0.34
iOS 10 on iPhone 6 Plus
### Problem

No image to choose when first authorized app to access photos, need to reopen the choosing dialog.

**Comment by jaggerwang** [comment]
@liaoyuan-io

**Comment by cnjsstong** [comment]
Looks like fixed in the new version of TZImagePickerController. Please upgrade and have a try.
