### ISSUE TITLE
ios模块添加能不能详细点。完全不知道怎么搞。安卓可以。

### ISSUE THREAD

**Issue by liliangzdh** [liaoyuan-io/react-native-multiple-image-picker#7]

**Comment by cnjsstong** [comment]
参考React Native文档中，手动链接的部分：
（英文，本库的2、3步对应这里的1、2步）
https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

（中文，本库的2、3步对应这里的1、2步）
http://wiki.jikexueyuan.com/project/react-native/linking-libraries.html

至于第三步，把`react-native-multiple-image-picker/ios/TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImagePickerController.bundle`拖进项目的Resources，并在项目的 Build Phases 下面的 Copy Bundle Resources 里添加它。
